Sherlock Helm Chart
metamx/sherlock pull request #7
Opened 2019-05-07 18:23 UTC by himadrisingh

2019-05-08 13:04 UTC, esevastyanov requested changes

2019-05-08 13:04 UTC, esevastyanov commented on chart/sherlock/Chart.yaml
> +- email: backend@quid.com
who is this? :)

2019-05-08 13:04 UTC, esevastyanov commented on chart/sherlock/values.yaml
> +namespace: falcon
it's likely there should be sherlock

2019-05-08 18:01 UTC, himadrisingh commented on chart/sherlock/Chart.yaml
> +- email: backend@quid.com
copy paste :P from other

2019-05-09 12:15 UTC, esevastyanov approved these changes

2019-05-15 04:24 UTC, merged